pipeline {
    environment {
            PATH = "C:\\WINDOWS\\SYSTEM32;${JAVA_HOME}\\bin"
    }
    agent {    label 'Grupp1JMeter'    }
    
    stages{
        stage('Run PrestaShop 100/50/30 threads/1/5/10min') {
            steps {
                bat "${JMETER_HOME}\\bin\\jmeter.bat -Jjmeter.save.saveservice.output_format=xml -n -t ${WORKSPACE}\\JMeter\\PrestashopTestplan.jmx -l ${WORKSPACE}\\JMeter\\jmeter_report.jtl"
                perfReport 'jmeter_report.jtl'
            }
        }
    }
    post {
        success {
            junit allowEmptyResults: true, testResults: "${WORKSPACE}\\test-results.xml"                   
        }
    }
}
